services:
  redis:
    image: 'bitnami/redis'
    env_file:
      - .env
    ports:
      - "6379:6379"
  vkr_tiler:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - satellite-data:/opt/satellite-data

volumes:
  satellite-data:
    external: true
    name: satellite-data